In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv('/content/developer_burnout_dataset_7000.csv')

In [4]:
data

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level,burnout_level
0,26.0,12.0,10.33,4.45,2.0,11.0,4.0,1.0,15.07,0.14,55.96,Medium
1,39.0,10.0,8.62,5.77,5.0,15.0,11.0,5.0,13.25,0.54,82.22,High
2,34.0,13.0,NaN,4.03,5.0,2.0,18.0,9.0,11.18,1.54,61.77,Medium
3,30.0,1.0,6.85,6.47,2.0,15.0,26.0,1.0,11.14,0.96,54.98,Medium
4,27.0,7.0,4.24,5.80,NaN,9.0,17.0,7.0,8.05,0.36,27.90,Low
...,...,...,...,...,...,...,...,...,...,...,...,...
6995,25.0,14.0,6.53,7.43,5.0,1.0,7.0,5.0,7.55,1.67,20.10,Low
6996,30.0,19.0,10.15,5.60,3.0,4.0,9.0,0.0,12.11,0.96,41.71,Medium
6997,44.0,8.0,8.56,6.80,5.0,18.0,3.0,4.0,11.62,1.04,80.15,High
6998,25.0,2.0,4.39,5.40,6.0,6.0,4.0,5.0,8.24,0.82,41.44,Medium
6999,25.0,2.0,4.35,4.83,1.0,16.0,23.0,4.0,8.52,1.98,39.18,Medium

In [5]:
data.isnull().sum()

age                 140
experience_years    140
daily_work_hours    140
sleep_hours         140
caffeine_intake     140
bugs_per_day        140
commits_per_day     140
meetings_per_day    140
screen_time         140
exercise_hours      140
stress_level        140
burnout_level       140
dtype: int64

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               6860 non-null   float64
 1   experience_years  6860 non-null   float64
 2   daily_work_hours  6860 non-null   float64
 3   sleep_hours       6860 non-null   float64
 4   caffeine_intake   6860 non-null   float64
 5   bugs_per_day      6860 non-null   float64
 6   commits_per_day   6860 non-null   float64
 7   meetings_per_day  6860 non-null   float64
 8   screen_time       6860 non-null   float64
 9   exercise_hours    6860 non-null   float64
 10  stress_level      6860 non-null   float64
 11  burnout_level     6860 non-null   object
dtypes: float64(11), object(1)
memory usage: 656.4+ KB

In [12]:
data.columns

Index(['age', 'experience_years', 'daily_work_hours', 'sleep_hours',
       'caffeine_intake', 'bugs_per_day', 'commits_per_day',
       'meetings_per_day', 'screen_time', 'exercise_hours', 'stress_level',
       'burnout_level'],
      dtype='object')

In [8]:
data['burnout_level'].value_counts()

burnout_level
Medium    3485
High      1782
Low       1593
Name: count, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['burnout_level']=le.fit_transform(data['burnout_level'])
data

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level,burnout_level
0,26.0,12.0,10.33,4.45,2.0,11.0,4.0,1.0,15.07,0.14,55.96,2
1,39.0,10.0,8.62,5.77,5.0,15.0,11.0,5.0,13.25,0.54,82.22,0
2,34.0,13.0,NaN,4.03,5.0,2.0,18.0,9.0,11.18,1.54,61.77,2
3,30.0,1.0,6.85,6.47,2.0,15.0,26.0,1.0,11.14,0.96,54.98,2
4,27.0,7.0,4.24,5.80,NaN,9.0,17.0,7.0,8.05,0.36,27.90,1
...,...,...,...,...,...,...,...,...,...,...,...,...
6995,25.0,14.0,6.53,7.43,5.0,1.0,7.0,5.0,7.55,1.67,20.10,1
6996,30.0,19.0,10.15,5.60,3.0,4.0,9.0,0.0,12.11,0.96,41.71,2
6997,44.0,8.0,8.56,6.80,5.0,18.0,3.0,4.0,11.62,1.04,80.15,0
6998,25.0,2.0,4.39,5.40,6.0,6.0,4.0,5.0,8.24,0.82,41.44,2
6999,25.0,2.0,4.35,4.83,1.0,16.0,23.0,4.0,8.52,1.98,39.18,2

In [27]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=10)
data['burnout_level']=knn.fit_transform(data[['burnout_level']])
data['burnout_level']

0       2.0
1       0.0
2       2.0
3       2.0
4       1.0
       ...
6995    1.0
6996    2.0
6997    0.0
6998    2.0
6999    2.0
Name: burnout_level, Length: 7000, dtype: float64

In [15]:
data['burnout_level'].isnull().sum()

np.int64(0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
data['experience_years']=sc.fit_transform(data[['experience_years']])
data['daily_work_hours']=sc.fit_transform(data[['daily_work_hours']])
data['sleep_hours']=sc.fit_transform(data[['sleep_hours']])
data['caffeine_intake']=sc.fit_transform(data[['caffeine_intake']])
data['bugs_per_day']=sc.fit_transform(data[['bugs_per_day']])
data['commits_per_day']=sc.fit_transform(data[['commits_per_day']])
data['meetings_per_day']=sc.fit_transform(data[['meetings_per_day']])
data['screen_time']=sc.fit_transform(data[['screen_time']])
data['exercise_hours']=sc.fit_transform(data[['exercise_hours']])
data['stress_level']=sc.fit_transform(data[['stress_level']])

data

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level,burnout_level
0,26.0,0.419916,0.464332,-1.408841,-0.674762,0.263829,-1.206390,-1.241019,1.001375,-1.504529,0.098408,2.0
1,39.0,0.072727,-0.132791,-0.495285,0.639138,0.959331,-0.398935,0.159267,0.412564,-0.810887,1.218479,0.0
2,34.0,0.593511,NaN,-1.699518,0.639138,-1.301049,0.408520,1.559554,-0.257127,0.923220,0.346223,2.0
3,30.0,-1.489623,-0.750865,-0.010823,-0.674762,0.959331,1.331325,-1.241019,-0.270067,-0.082562,0.056608,2.0
4,27.0,-0.448056,-1.662262,-0.474522,NaN,-0.083921,0.293169,0.859411,-1.269751,-1.123026,-1.098438,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6995,25.0,0.767105,-0.862607,0.653581,0.639138,-1.474925,-0.860338,0.159267,-1.431512,1.148653,-1.431132,1.0
6996,30.0,1.635078,0.401477,-0.612940,-0.236796,-0.953299,-0.629637,-1.591091,0.043749,-0.082562,-0.509399,2.0
6997,44.0,-0.274461,-0.153742,0.217566,0.639138,1.480957,-1.321741,-0.190804,-0.114777,0.056166,1.130187,0.0
6998,25.0,-1.316028,-1.609883,-0.751357,1.077104,-0.605548,-1.206390,0.159267,-1.208282,-0.325337,-0.520915,2.0
6999,25.0,-1.316028,-1.623850,-1.145847,-1.112729,1.133206,0.985273,-0.190804,-1.117695,1.686226,-0.617311,2.0

In [20]:
data.isnull().sum()

age                 140
experience_years    140
daily_work_hours    140
sleep_hours         140
caffeine_intake     140
bugs_per_day        140
commits_per_day     140
meetings_per_day    140
screen_time         140
exercise_hours      140
stress_level        140
burnout_level         0
dtype: int64

In [25]:
from sklearn.impute import KNNImputer
knn=KNNImputer(n_neighbors=5)
data['stress_level']=knn.fit_transform(data[['stress_level']])
data

,age,experience_years,daily_work_hours,sleep_hours,caffeine_intake,bugs_per_day,commits_per_day,meetings_per_day,screen_time,exercise_hours,stress_level,burnout_level
0,26.0,0.419916,0.464332,-1.408841,-0.674762,0.263829,-1.206390,-1.241019,1.001375,-1.504529,0.098408,2.0
1,39.0,0.072727,-0.132791,-0.495285,0.639138,0.959331,-0.398935,0.159267,0.412564,-0.810887,1.218479,0.0
2,34.0,0.593511,NaN,-1.699518,0.639138,-1.301049,0.408520,1.559554,-0.257127,0.923220,0.346223,2.0
3,30.0,-1.489623,-0.750865,-0.010823,-0.674762,0.959331,1.331325,-1.241019,-0.270067,-0.082562,0.056608,2.0
4,27.0,-0.448056,-1.662262,-0.474522,NaN,-0.083921,0.293169,0.859411,-1.269751,-1.123026,-1.098438,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6995,25.0,0.767105,-0.862607,0.653581,0.639138,-1.474925,-0.860338,0.159267,-1.431512,1.148653,-1.431132,1.0
6996,30.0,1.635078,0.401477,-0.612940,-0.236796,-0.953299,-0.629637,-1.591091,0.043749,-0.082562,-0.509399,2.0
6997,44.0,-0.274461,-0.153742,0.217566,0.639138,1.480957,-1.321741,-0.190804,-0.114777,0.056166,1.130187,0.0
6998,25.0,-1.316028,-1.609883,-0.751357,1.077104,-0.605548,-1.206390,0.159267,-1.208282,-0.325337,-0.520915,2.0
6999,25.0,-1.316028,-1.623850,-1.145847,-1.112729,1.133206,0.985273,-0.190804,-1.117695,1.686226,-0.617311,2.0

In [22]:
data.isnull().sum()

age                 140
experience_years    140
daily_work_hours    140
sleep_hours         140
caffeine_intake     140
bugs_per_day        140
commits_per_day     140
meetings_per_day    140
screen_time         140
exercise_hours      140
stress_level          0
burnout_level         0
dtype: int64