In [ ]:
import numpy as np
import pandas as pd
from sklearn.linear_model  import LinearRegression

In [ ]:
data=pd.read_csv('/content/tested.csv')
data

     PassengerId  Survived  Pclass  ...      Fare Cabin  Embarked
0            892         0       3  ...    7.8292   NaN         Q
1            893         1       3  ...    7.0000   NaN         S
2            894         0       2  ...    9.6875   NaN         Q
3            895         0       3  ...    8.6625   NaN         S
4            896         1       3  ...   12.2875   NaN         S
..           ...       ...     ...  ...       ...   ...       ...
413         1305         0       3  ...    8.0500   NaN         S
414         1306         1       1  ...  108.9000  C105         C
415         1307         0       3  ...    7.2500   NaN         S
416         1308         0       3  ...    8.0500   NaN         S
417         1309         0       3  ...   22.3583   NaN         C

[418 rows x 12 columns]

In [ ]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
data['Age'].max()

76.0

In [ ]:
data.fillna(0).max(numeric_only=True)

PassengerId    1309.0000
Survived          1.0000
Pclass            3.0000
Age              76.0000
SibSp             8.0000
Parch             9.0000
Fare            512.3292
dtype: float64

In [ ]:
data['Age'].fillna(data['Age'].mean(),inplace=True)

/tmp/ipykernel_3128/2853692610.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data['Age'].fillna(data['Age'].mean(),inplace=True)

In [ ]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          327
Embarked         0
dtype: int64

In [ ]:
data['Cabin'].fillna('Unknown', inplace=True)

In [ ]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          418 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         418 non-null    float64
 10  Cabin        418 non-null    object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [ ]:
data.value_counts('PassengerId')

PassengerId
1309    1
892     1
1293    1
1292    1
1291    1
       ..
898     1
897     1
896     1
895     1
894     1
Name: count, Length: 418, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
data['Name']=le.fit_transform(data['Name'])
data['Sex']=le.fit_transform(data['Sex'])
data['Ticket']=le.fit_transform(data['Ticket'])
data['Cabin']=le.fit_transform(data['Cabin'])
data['Embarked']=le.fit_transform(data['Embarked'])
data

     PassengerId  Survived  Pclass  Name  ...  Ticket      Fare  Cabin  Embarked
0            892         0       3   206  ...     152    7.8292     76         1
1            893         1       3   403  ...     221    7.0000     76         2
2            894         0       2   269  ...      73    9.6875     76         1
3            895         0       3   408  ...     147    8.6625     76         2
4            896         1       3   178  ...     138   12.2875     76         2
..           ...       ...     ...   ...  ...     ...       ...    ...       ...
413         1305         0       3   353  ...     267    8.0500     76         2
414         1306         1       1   283  ...     324  108.9000     22         0
415         1307         0       3   332  ...     346    7.2500     76         2
416         1308         0       3   384  ...     220    8.0500     76         2
417         1309         0       3   302  ...     105   22.3583     76         0

[418 rows x 12 columns]

In [ ]:
x=data.drop(['Survived'],axis=1)
y=data['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=40)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
cm=confusion_matrix(y_test,y_pred)
cm
accuracy=accuracy_score(y_test,y_pred)
accuracy

1.0

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)

1.0

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
accuracy_score(y_test,y_pred)
conf=confusion_matrix(y_test,y_pred)
print(conf)

[[82  0]
 [ 0 44]]